name: Building Blocks

on: 
    #this will not automatically run the pipeline , you manually have to run the 
    workflow_dispatch: 

# here jobs run parellel it will create a new vm for every job 
# here all steps run sequentially 
jobs:  
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello 
              run: echo " Hello, world!"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Failed step
            # | this command will help you execute more than one command in one step 

              run:  |
                    echo "This step will fail"
                    exit 0
            #if any step fail then all the steps below also will not execute 
            - name: Say goodbye
              run: echo "Goodbye, world!"