name: Using Expressions
run-name: Using Expressions | DEBUG - ${{inputs.debug && 'ON' || 'OFF'}}
#inputs.debug && 'ON' || 'OFF' (inputs.debug == true then it go to the 'ON' else 
#it goes to the 'OFF')
#DEBUG - ON || DEBUG - OFF


on:
    workflow_dispatch:

        #input option like a checkbox while running workflow
        inputs:
            debug:
                type: boolean
                default: false


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            #It will only run in the Debug mode
            - name: '[Debug] Print start-up data'
              if: inputs.debug
              run: |
                echo "Triggered by: ${{github.event_name}}"
                echo "Branch: ${{github.ref_name}}"
                echo "Commit SHA: ${{github.sha}}"
                echo "Actor: ${{github.actor}}"
                echo "Runner OS: ${{runner.os}}"
                echo "Workflow: ${{github.workflow}}"

            - name: '[Debug] Print when triggered from main'
              if: inputs.debug && github.ref_name=='main'
              run: echo "This workflow was triggered from the main branch"
            - name: Greeting
              run: echo "Hello, ${{github.actor}}! Welcome to the Using Expressions workflow."
