name: PR Gatekeeper

on:
    # pull_request:
    #     branches:
    #         - main
    workflow_dispatch: 

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Show merging branch
            #base_ref show the branch where the pr is being merge into 
              run: echo "The PR is being merged into ${{github.base_ref}}"

            - name: Show PR number
              run: echo "The PR number is ${{github.event.pull_request.number}}"

            - name: Complete 
              run: echo "Gatekeeper checks complete"
